eg_trajectory_controller:
  type: "position_controllers/JointTrajectoryController"
  joints:
    - left_ezgripper_knuckle_palm_L1_1
    - left_ezgripper_knuckle_palm_L1_2
  constraints:
      goal_time: 0.6
      stopped_velocity_tolerance: 0.05
      left_ezgripper_knuckle_palm_L1_1: {trajectory: 0.3, goal: 0.1}
      left_ezgripper_knuckle_palm_L1_2: {trajectory: 0.3, goal: 0.1}
  stop_trajectory_duration: 0.5
  state_publish_rate:  25
  action_monitor_rate: 10
  allow_partial_joints_goal: true
